#!/usr/bin/env python3
"""
Example workflow for video synthesis with the updated directory structure.

This script demonstrates how to use video synthesis after running:
./run.sh --style-config hkcomic

The MP3 audio files and slide images are now stored in the same visuals directory.
"""

import sys
from pathlib import Path

# Add current directory to path
sys.path.insert(0, '.')

def demonstrate_workflow():
    """Demonstrate the video synthesis workflow."""
    print("Video Synthesis Workflow with Same Directory Structure")
    print("=" * 60)
    
    print("\n1. First, run the presentation processing:")
    print("   ./run.sh --style-config hkcomic")
    print("   This generates:")
    print("   - Speaker notes")
    print("   - Visual slide images (PNG)")
    print("   - TTS audio files (MP3)")
    print("   - All files are stored in the same visuals directory")
    
    print("\n2. Directory structure after processing:")
    print("   generate/hkcomic/")
    print("   └── presentation_en_visuals/")
    print("       ├── slide_1_reimagined.png")
    print("       ├── slide_1_<hash>.mp3")
    print("       ├── slide_2_reimagined.png")
    print("       ├── slide_2_<hash>.mp3")
    print("       └── ...")
    
    print("\n3. Synthesize video using CLI (separate directories):")
    print("   python main.py --synthesize-video \\")
    print("     --slides-dir generate/hkcomic/presentation_en_visuals \\")
    print("     --audio-dir generate/hkcomic/presentation_en_speech \\")
    print("     --video-output generate/hkcomic/presentation_video.mp4")
    
    print("\n4. Or using the integration API:")
    print("   from services.video_synthesis.integration import VideoSynthesisIntegration")
    print("   integration = VideoSynthesisIntegration(config)")
    print("   video_path = integration.create_video_from_visuals_directory(presentation)")
    
    print("\n5. Configuration options:")
    print("   # Default (Full HD)")
    print("   python main.py --synthesize-video --slides-dir visuals/ --audio-dir speech/ --video-output video.mp4")
    print("   ")
    print("   # HD with custom settings")
    print("   python main.py --synthesize-video \\")
    print("     --slides-dir visuals/ \\")
    print("     --audio-dir speech/ \\")
    print("     --video-output video_hd.mp4 \\")
    print('     --video-config \'{"resolution": [1280, 720], "video_bitrate": "1.5M"}\'')
    print("   ")
    print("   # 4K high quality")
    print("   python main.py --synthesize-video \\")
    print("     --slides-dir visuals/ \\")
    print("     --audio-dir speech/ \\")
    print("     --video-output video_4k.mp4 \\")
    print('     --video-config \'{"resolution": [3840, 2160], "video_bitrate": "8M"}\'')


def test_configuration():
    """Test the configuration to ensure directories are aligned."""
    print("\n" + "=" * 60)
    print("Testing Configuration")
    print("=" * 60)
    
    try:
        from config.config import Config
        
        # Test configuration
        config = Config(
            pptx_path='presentation.pptx',
            pdf_path='presentation.pdf',
            language='en',
            style='hkcomic'
        )
        
        print(f"✓ Visuals directory: {config.visuals_dir}")
        print(f"✓ Speech directory: {config.speech_dir}")
        print(f"✓ Same directory: {config.visuals_dir == config.speech_dir}")
        
        if config.visuals_dir == config.speech_dir:
            print("✓ Configuration is correct - MP3 and images in same directory")
        else:
            print("✗ Configuration issue - directories should be the same")
            
    except Exception as e:
        print(f"✗ Configuration test failed: {e}")


def show_file_patterns():
    """Show the expected file patterns in the visuals directory."""
    print("\n" + "=" * 60)
    print("Expected File Patterns")
    print("=" * 60)
    
    print("\nSlide Images (generated by visual processing):")
    print("  slide_1_reimagined.png")
    print("  slide_2_reimagined.png")
    print("  slide_3_reimagined.png")
    print("  ...")
    
    print("\nAudio Files (generated by TTS):")
    print("  slide_1_<hash>.mp3")
    print("  slide_2_<hash>.mp3") 
    print("  slide_3_<hash>.mp3")
    print("  ...")
    
    print("\nVideo Synthesis Process:")
    print("  1. Find all PNG files matching slide_*_reimagined.png")
    print("  2. Find all MP3 files matching slide_*.mp3")
    print("  3. Pair them by slide number")
    print("  4. Create video segments with slide duration = audio duration")
    print("  5. Concatenate all segments into final video")


def main():
    """Main function."""
    demonstrate_workflow()
    test_configuration()
    show_file_patterns()
    
    print("\n" + "=" * 60)
    print("Ready to use video synthesis!")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Run: ./run.sh --style-config hkcomic")
    print("2. Wait for processing to complete")
    print("3. Run video synthesis on the generated visuals directory")
    print("4. Enjoy your presentation video!")


if __name__ == "__main__":
    main()